Project 1/website/views.py
from flask import Blueprint, render_template, request, flash, jsonify
from flask_login import login_required, current_user
from .models import Note, User, NoteName, EventSignup

from . import db
import json


views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
# users should be logged in to view the home page
@login_required
def home():

    return render_template("home.html", user=current_user)

@views.route('/events', methods=['GET', 'POST'])
# users should be logged in to view the home page
@login_required
def events():

    return render_template("events.html")


@views.route('/event-signup', methods=['GET', 'POST'])
def event_signup_page():
    if current_user.is_authenticated:
        if request.method == 'POST':
            name = request.form['name']
            age = request.form['age']
            phone = request.form['phone']
            email = request.form['email']
            time = request.form['time']
            introduction = request.form['introduction']

            new_signup = EventSignup(name=name, age=age, phone=phone, email=email, time=time, introduction=introduction)

            db.session.add(new_signup)
            db.session.commit()

            flash('You have successfully signed up for the event!', 'success')

            return render_template('home.html', user=current_user)
        else:
            return render_template('event-signup.html', user=current_user)
    else:
        flash('You need to login first!', 'warning')
        return render_template('login.html')




@views.route('/note', methods=['GET', 'POST'])
# users should be logged in to view the note page
@login_required
def note():
    if request.method == 'POST': 
        note = request.form.get('note')
        note_name = request.form.get('name')

        if len(note) < 1:
            flash('Your review is too short!', category='error') 
        else:
            new_note_name = NoteName(name=note_name)
            new_note = Note(data=note, user_id=current_user.id, note_name=new_note_name)              
            #adding the note with name to the database 
            db.session.add(new_note_name)
            db.session.add(new_note) #adding the note to the database 
            db.session.commit()
            flash('Your Note is recorded!', category='success')

    return render_template("note.html", user=current_user)


@views.route('/delete-note', methods=['POST'])
def delete_note():  
    note = json.loads(request.data) # this function expects a JSON from the INDEX.js file 
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})

Project 1/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>


    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- links to external files: the Bootstrap CSS and Font Awesome CSS files -->
    <!-- Instead of building my own CSS file, bootstrap is more powerful and time-saving -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Sofia"
      crossorigin="anonymous"
    />
    <link 
    href="https://fonts.googleapis.com/css?family=Merriweather|Roboto+Slab&display=swap" 
    rel="stylesheet">
    <link 
      rel="stylesheet" 
      href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" 
      integrity="sha384-9aItS2sj4gD2QxJ3gRxgz4TH4Y/HJU2+Bjen+GvXuFP+Fd/maIljen+GvXuFP+Fd" 
      crossorigin="anonymous">
    <title>{% block title %}My Own Notes{% endblock %}</title>
    <style>
      body {
        background-color: #e6ffe6;
    }

    * {
        box-sizing: border-box;
    }

    .container {
        margin: 50px;
        font-family: 'Merriweather', sans-serif;
        font-size: 1.5rem;
    }

    #sm-footer {

        bottom: 0;
        background-color: black;
        width: 100vw;
        height: 15vh;
        display: flex;
        justify-content: space-evenly;
        font-size: 2rem;
        font-family: 'Roboto Slab', sans-serif;
    }

    a,
    a:visited {
        color: white;
        text-decoration: none;
        padding: 10px;
    }
    #sm-footer h4 {
      color: #a6a6a6;
      font-size: 0.7 rem;
    }
    #sm-footer h5 {
      color: #a6a6a6;
      font-size: 0.5 rem;
    }
    #sm-footer a {
      color: #ffffff;
      font-size: 1.2 rem;
    }
    .my-button {
  background-color: #FFC107;
  color: #FFF;
  border: none;
  border-radius: 4px;
  padding: 8px 16px;
  font-size: 16px;
  font-weight: bold;
  text-transform: uppercase;
  text-decoration: none;
}

.my-button:hover {
  background-color: #FFA000;
}

    
      
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- a button to toggle the collapse of the navigation bar on mobile devices (smaller screen) -->
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <!-- if the user is logged in, she/he will see 'home' and 'logout' in the nav-bar. -->

          {% if user.is_authenticated %}
          <button type="button" class="btn btn-light mr-2" onclick="location.href='/'">Home</button>
          <button type="button" class="btn btn-light mr-2" onclick="location.href='/events'">View the upcoming events</button>
          <button type="button" class="btn btn-light mr-2" onclick="location.href='/event-signup'">Sign up for upcoming events</button>
          <button type="button" class="btn btn-secondary mr-2" onclick="location.href='/logout'">Logout</button>
          {% else %}
          <button type="button" class="btn btn-light mr-2" onclick="location.href='/login'">Login</button>
          <button type="button" class="btn btn-light mr-2" onclick="location.href='/sign-up'">Sign Up</button>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories = true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>






    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    >
  </script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  
  <footer id="sm-footer">
    <a href="https://www.facebook.com">Facebook<i class="fab fa-facebook"></i></a>
       <a href="https://www.instagram.com">Instagram<i class="fab fa-instagram"></i></a>
       <a href="https://www.twitter.com">Twitter<i class="fab fa-twitter"></i></a>
       <a href="https://youtube.com">Youtube<i class="fab fa-youtube"></i></a>
       <a href="https://linkedin.com">Linkedin<i class="fab fa-linkedin"></i></a>
       <div class="col-md-5">
        <h4>Contact us:</h4>
        <h5>Email: your-email@example.com</h5>
        <h5>Phone: (123) 456-7890</h5>
      </div>


</footer>
</body>
</html>

Project 1/website/templates/event-signup.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <h1>Event Sign Up</h1>
        <h4>Welcome to our event sign-up page! Thank you for your interest in our activities. Now please fill in your information so as others can know about you!</h4>
        <form method="POST" action="{{ url_for('views.event_signup_page') }}">
            <input type="hidden" name="event_id" value="{{ event_id }}">
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" name="name" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="age">Age:</label>
                <input type="number" name="age" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="phone">Phone Number:</label>
                <input type="text" name="phone" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="email">Email:</label>
                <input type="email" name="email" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="time">Time Able to Attend:</label>
                <select name="time" class="form-control" required>
                    <option value="">Select Time</option>
                    <option value="9:00-10:00am">9:00-10:00am</option>
                    <option value="10:00-11:00am">10:00-11:00am</option>
                    <option value="11:00-12:00pm">11:00-12:00pm</option>
                    <option value="12:00-1:00pm">12:00-1:00pm</option>
                    <option value="1:00-2:00pm">1:00-2:00pm</option>
                    <option value="2:00-3:00pm">2:00-3:00pm</option>
                    <option value="3:00-4:00pm">3:00-4:00pm</option>
                    <option value="4:00-5:00pm">4:00-5:00pm</option>
                    <option value="5:00-6:00pm">5:00-6:00pm</option>
                    <option value="6:00-7:00pm">6:00-7:00pm</option>
                    <option value="7:00-8:00pm">7:00-8:00pm</option>
                    <option value="8:00-9:00pm">8:00-9:00pm</option>
                    <option value="9:00-10:00pm">9:00-10:00pm</option>
                    <option value="10:00-11:00pm">10:00-11:00pm</option>
                    <option value="11:00-12:00am">11:00-12:00am</option>
                    <option value="12:00-1:00am">12:00-1:00am</option>
                </select>
            </div>
            <div class="form-group">
                <label for="introduction">Introduction:</label>
                <textarea name="introduction" class="form-control" required></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

Project 1/website/templates/events.html
{% extends 'base.html' %}
{% block title %}Events{% endblock %} 
{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Welcome to our Volunteer Events!</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <img src="/images/bbq.jpeg" class="card-img-top" alt="Event 1">
          <div class="card-body">
            <h5 class="card-title">Event 1</h5>
            <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum viverra turpis euismod urna rhoncus ultricies.</p>
            <a href="#" class="btn btn-primary">Sign Up</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <img src="/images/bbq.jpeg" class="card-img-top" alt="Event 2">
          <div class="card-body">
            <h5 class="card-title">Event 2</h5>
            <p class="card-text">Pellentesque consectetur, ipsum vel lobortis malesuada, nisi neque faucibus velit, non scelerisque urna felis eget metus.</p>
            <a href="#" class="btn btn-primary">Sign Up</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <img src="/images/bbq.jpeg" class="card-img-top" alt="Event 3">
          <div class="card-body">
            <h5 class="card-title">Event 3</h5>
            <p class="card-text">Sed euismod lacinia lectus, non bibendum est malesuada eu. Morbi nec mauris ut augue consectetur euismod.</p>
            <a href="#" class="btn btn-primary">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="card">
          <img src="/images/bbq.jpeg" class="card-img-top" alt="Event 4">
          <div class="card-body">
            <h5 class="card-title">Event 4</h5>
            <p class="card-text">Integer nec enim vitae eros fermentum malesuada. Vivamus euismod lacus id nisl congue, quis faucibus est vulputate.</p>
            <a href="#" class="btn btn-primary">Sign Up</a>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card">
          <img src="/images/bbq.jpeg" class="card-img-top" alt="Event 5">
          <div class="card-body">
            <h5 class="card-title">Event 5</h5>
            <p class="card-text">Vivamus vulputate, sapien vel lobortis hendrerit, nisi velit lobortis nisi, id consectetur nunc elit in quam.</p>
            <a href="#" class="btn btn-primary">Sign Up</a>
          </div>
          <div class="col-md-4">
            <div class="card">
              <img src="/images/bbq.jpeg" class="card-img-top" alt="Event 6">
              <div class="card-body">
                <h5 class="card-title">Event 6</h5>
                <p class="card-text">Donec vitae urna libero. Sed vehicula nibh ac ex bibendum aliquam. Maecenas maximus tortor dolor, vitae vestibulum nulla vestibulum vel.</p>
                <a href="#" class="btn btn-primary">Sign Up</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer text-muted">1234</div>
    {% endblock %}

Project 1/website/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %} 
{% block content %}
  <div class="container">
    <h1>Welcome to Our Organization!</h1>
    <p>We are a non-profit organization dedicated to helping people in need.</p>
    <p>Our mission is to provide assistance to those who are struggling with poverty, homelessness, and other difficult circumstances.</p>
    <p>Through our programs and services, we strive to make a positive impact on the lives of those we serve.</p>
    <p>Thank you for your support!</p>
  </div>
{% endblock %}

Project 1/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <!-- align = "center" is no longer used -->
  <h3 class="mt-5" style="text-align: center; ">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder=""name@example.com"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

Project 1/website/templates/logout.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
    %}
    <form method="POST">
      <h3 style="text-align: center;">Login</h3>
      <div class="form-group">
        <label for="email">Email Address</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        />
      </div>
      <div class="form-group">
        <label for="password">Password</label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <button type="submit" class="btn btn-primary">Login</button>
    </form>
    {% endblock %}
    

Project 1/website/templates/note.html
{% extends "base.html" %} 
{% block title %}Note{% endblock %} 
{% block content %}


 <!-- align="center" is no longer supported -->


<div class="container-fluid mt-4 mb-4" >
  <h1 class="my-5 text-center" >My Own Secret Notebook</h1>
</div>

<ul class="list-group list-group-flush" id="notes">
  {% for note in user.notes %}
  <li class="list-group-item">
    {{ note.note_name.name }}
    {{ note.data }}
    <p>{{ note.date.strftime('%Y-%m-%d %H:%M:%S') }}</p>
    <button type="button" class="close" onClick="deleteNote({{ note.id }})">
      <span aria-hidden="true">&times;</span>
    </button>
  </li>
  {% endfor %}
</ul>

<div class="row">
  <!-- width adjusted -->
  <div class="col-4">
    <div class="form-group">
      <h2><label for="name" style="font-weight: bold;">Title</label></h2>
      <input type="text" name="note_name" id="note_name" class="form-control" required>
    </div>
  </div>
</div>

<!-- The size of the title input box is adjusted to make the page look nicer -->
<!-- <div class="form-group">
  <h4><label for="name">Title</label></h4>
  <input type="text" name="note_name" id="note_name" class="form-control" required>
</div> -->


<form method="POST">
  <textarea name="note" id="note" class="form-control" style="height: 300px; width: 70%;"></textarea>
  <br />
  <div style="text-align: left;">
    <button type="submit" class="btn btn-primary ml-auto mr-10">Record this</button>
  </div>
</form>
</form>

{% endblock %}

Project 1/website/templates/sign-up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 style="text-align: center;">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}